export default {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CURRENT_ERROR: 'SET_CURRENT_ERROR',
  INCREMENT_USER_REQUESTS_COUNTER: 'INCREMENT_USER_REQUESTS_COUNTER',
  DECREMENT_USER_REQUESTS_COUNTER: 'DECREMENT_USER_REQUESTS_COUNTER',
  UPDATE_USER: 'UPDATE_USER',
};
